-- =====================================================================
--  RENT IN SUN · Configuración de la base de datos (Supabase)
--  Pega TODO este archivo en Supabase → SQL Editor → New query → Run.
--  Se puede ejecutar varias veces sin problema.
-- =====================================================================

-- ---------- Administradores ----------
create table if not exists public.admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);
alter table public.admins enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (select 1 from public.admins where user_id = auth.uid());
$$;
revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;

drop policy if exists "admins_self_read" on public.admins;
create policy "admins_self_read" on public.admins
  for select to authenticated using (user_id = auth.uid());

-- ---------- Propiedades (datos públicos) ----------
create table if not exists public.properties (
  id bigint generated by default as identity (start with 1000) primary key,
  published boolean not null default true,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.properties enable row level security;

drop policy if exists "properties_public_read" on public.properties;
create policy "properties_public_read" on public.properties
  for select to anon, authenticated using (published or public.is_admin());

drop policy if exists "properties_admin_insert" on public.properties;
create policy "properties_admin_insert" on public.properties
  for insert to authenticated with check (public.is_admin());

drop policy if exists "properties_admin_update" on public.properties;
create policy "properties_admin_update" on public.properties
  for update to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "properties_admin_delete" on public.properties;
create policy "properties_admin_delete" on public.properties
  for delete to authenticated using (public.is_admin());

-- ---------- Datos privados de cada propiedad (propietario, notas, comisión) ----------
create table if not exists public.property_private (
  property_id bigint primary key references public.properties(id) on delete cascade,
  owner jsonb not null default '{}'::jsonb,
  notes text not null default '',
  commission numeric
);
alter table public.property_private enable row level security;

drop policy if exists "private_admin_all" on public.property_private;
create policy "private_admin_all" on public.property_private
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- ---------- Solicitudes (reservas, contacto, propietarios) ----------
create table if not exists public.leads (
  id bigint generated always as identity primary key,
  created_at timestamptz not null default now(),
  type text not null check (char_length(type) <= 80),
  name text check (char_length(name) <= 120),
  email text check (char_length(email) <= 160),
  phone text check (char_length(phone) <= 40),
  property text check (char_length(property) <= 200),
  detail text check (char_length(detail) <= 4000),
  lang text check (lang in ('es','en','fr','sv')),
  status text not null default 'nueva' check (status in ('nueva','contactada','cerrada'))
);
alter table public.leads enable row level security;

drop policy if exists "leads_public_insert" on public.leads;
create policy "leads_public_insert" on public.leads
  for insert to anon, authenticated with check (status = 'nueva');

drop policy if exists "leads_admin_read" on public.leads;
create policy "leads_admin_read" on public.leads
  for select to authenticated using (public.is_admin());

drop policy if exists "leads_admin_update" on public.leads;
create policy "leads_admin_update" on public.leads
  for update to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "leads_admin_delete" on public.leads;
create policy "leads_admin_delete" on public.leads
  for delete to authenticated using (public.is_admin());

-- ---------- Ajustes de la web (contacto, imágenes generales) ----------
create table if not exists public.settings (
  key text primary key,
  value jsonb not null default '{}'::jsonb
);
alter table public.settings enable row level security;

drop policy if exists "settings_public_read" on public.settings;
create policy "settings_public_read" on public.settings
  for select to anon, authenticated using (true);

drop policy if exists "settings_admin_write" on public.settings;
create policy "settings_admin_write" on public.settings
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- ---------- Permisos de tabla ----------
grant select on public.properties, public.settings to anon, authenticated;
grant insert on public.leads to anon, authenticated;
grant select, insert, update, delete on public.properties, public.property_private, public.leads, public.settings to authenticated;
grant select on public.admins to authenticated;

-- ---------- Almacenamiento de fotos ----------
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('fotos', 'fotos', true, 10485760, array['image/jpeg','image/png','image/webp'])
on conflict (id) do update set public = true, file_size_limit = 10485760,
  allowed_mime_types = array['image/jpeg','image/png','image/webp'];

drop policy if exists "fotos_admin_insert" on storage.objects;
create policy "fotos_admin_insert" on storage.objects
  for insert to authenticated with check (bucket_id = 'fotos' and public.is_admin());

drop policy if exists "fotos_admin_update" on storage.objects;
create policy "fotos_admin_update" on storage.objects
  for update to authenticated using (bucket_id = 'fotos' and public.is_admin());

drop policy if exists "fotos_admin_delete" on storage.objects;
create policy "fotos_admin_delete" on storage.objects
  for delete to authenticated using (bucket_id = 'fotos' and public.is_admin());

drop policy if exists "fotos_admin_select" on storage.objects;
create policy "fotos_admin_select" on storage.objects
  for select to authenticated using (bucket_id = 'fotos' and public.is_admin());

-- ---------- Datos de contacto iniciales ----------
insert into public.settings (key, value) values
  ('contact', '{"phone":"+34 622 773 790","wa":"34622773790","email":"info@rentinsun.com","address":"Paseo de Cotobro Edificio Delfín Portal 1","city":"18690 Almuñécar, Granada"}')
on conflict (key) do nothing;

-- =====================================================================
--  PASO FINAL: dar permisos de administrador a tu usuario.
--  1) Crea antes el usuario en Authentication → Users → Add user.
--  2) Cambia el email de abajo por el tuyo y ejecuta SOLO esta línea.
-- =====================================================================
-- insert into public.admins (user_id) select id from auth.users where email = 'info@rentinsun.com' on conflict do nothing;
